<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-SmartInventory.Inventories.WebApi-8E7826A4-6526-4C5A-A60C-68B13F5E73D3</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.2" NoWarn="NU1605" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="8.0.2" NoWarn="NU1605" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Identity.Web" Version="2.15.2" />
        <PackageReference Include="Microsoft.Identity.Web.DownstreamApi" Version="2.15.2" />
        <PackageReference Include="OpenTelemetry" Version="1.14.0" />
        <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.14.0" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.14.0" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.14.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.14.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.14.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.14.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
        <PackageReference Include="Serilog.Sinks.OpenTelemetry" Version="4.2.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="8.1.4" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="8.1.4" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="../SmartInventory.Inventories.Queries.Infra.In.RestApi/SmartInventory.Inventories.Queries.Infra.In.RestApi.csproj" />
      <ProjectReference Include="../SmartInventory.Inventories.Queries.Infra.Out.Repository/SmartInventory.Inventories.Queries.Infra.Out.Repository.csproj" />
      <ProjectReference Include="../SmartInventory._Framework.Util/SmartInventory._Framework.Util.csproj" />
      <ProjectReference Include="..\SmartInventory.Inventories.Commands.AntiCorruption.In.DomainEvents\SmartInventory.Inventories.Commands.AntiCorruption.In.DomainEvents.csproj" />
      <ProjectReference Include="..\SmartInventory.Inventories.Commands.Infra.In.RestApi\SmartInventory.Inventories.Commands.Infra.In.RestApi.csproj" />
      <ProjectReference Include="..\SmartInventory.Inventories.Infra.Out.Repository\SmartInventory.Inventories.Infra.Out.Repository.csproj" />
      <ProjectReference Include="..\SmartInventory._Framework.DomainModel\SmartInventory._Framework.DomainModel.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Migrations\" />
    </ItemGroup>

</Project>
