<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>SmartInventory.Inventories.Repository</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SmartInventory._Framework.DomainModel\SmartInventory._Framework.DomainModel.csproj" />
      <ProjectReference Include="..\SmartInventory._Framework.Infra.Out.Repository\SmartInventory._Framework.Infra.Out.Repository.csproj" />
    </ItemGroup>

</Project>
