<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>SmartInventory._Framework.Infra.Out.Repository</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.5.1" />
      <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SmartInventory._Framework.DomainModel\SmartInventory._Framework.DomainModel.csproj" />
    </ItemGroup>

</Project>
